### ISSUE TITLE
[FEAT]: Provide direct access to all workflow runs through repository node

### ISSUE THREAD

**Issue by QimbE** [octokit/octokit.graphql.net#310]
### Describe the need

If you want to build a query to access runs of workflow in some repository you should write great amount of code, requesting a lot of useless nodes. It is very common to face the rate limited response, or even node limit overflow response. Please add direct access to workflow runs.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kfcampbell** [comment]
Hi @QimbE, I'm not sure what you mean here. It sounds like you're asking for additional functionality to be added at the API level, is that right? Are there changes specific to this package you can envision to do this?

**Comment by QimbE** [comment]
> It sounds like you're asking for additional functionality to be added at the API level, is that right?
Yep
> Are there changes specific to this package you can envision to do this?
No then

**Comment by kfcampbell** [comment]
In that case, making a request in the [community discussions for GitHub's API](https://github.com/orgs/community/discussions/categories/api-and-webhooks) would be more appropriate. I'm going to close this for now since there's nothing the project can do specifically unless that behavior is changed at the API level.

**Comment by kfcampbell** [comment]
In that case, making a request in the [community discussions for GitHub's API](https://github.com/orgs/community/discussions/categories/api-and-webhooks) would be more appropriate. I'm going to close this for now since there's nothing the project can do specifically unless that behavior is changed at the API level.
